### ISSUE TITLE
Could not send request 

### ISSUE THREAD

**Issue by Ritibhandari16** [JamesMessinger/super-powered-api-testing#1]
As I am new to API testing, please help me with this issue. How I can get the API key. 
![api](https://user-images.githubusercontent.com/31196723/125797850-26a2f904-a044-4e04-b8b3-5c5252dae50c.PNG)

refer to the attached image. 
Thanks in advance!

**Comment by JamesMessinger** [comment]
You need to create a [Postman variable](https://learning.postman.com/docs/sending-requests/variables/) named `{{api_root}}` that contains the root part of the API's URL (e.g. `http://localhost/` or whatever).
